name: oref
description: "Imperative state management"
version: 0.0.0
repository: https://github.com/odroe/odroe

environment:
  sdk: ^3.5.3
  # flutter: ">=1.17.0"

dependencies:
  # flutter:
  #   sdk: flutter

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
