name: oref
description: Oref is a lightweight, high-performance reactive programming library.
version: 0.2.0
repository: https://github.com/odroe/odroe/tree/main/pub/oref
homepage: https://odroe.dev
issue_tracker: https://github.com/odroe/odroe/issues
resolution: workspace

funding:
  - https://github.com/sponsors/medz

topics:
  - state
  - reactive
  - ref
  - derived
  - effect

environment:
  sdk: ^3.5.3

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
