name: _octr
description: Internal package, The _octr is odroe/odroe packages shared container.
version: 0.0.1
resolution: workspace
repository: https://github.com/odroe/odroe

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
