name: playground
description: "Odroe playground"
publish_to: "none"
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  oref_flutter:
    path: ../pub/oref_flutter
  oncecall:
    path: ../pub/oncecall

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
