name: setup
description: >-
  Setup - A Progressive reactivity framework.
  An approachable, performant, and versatile framework for building Flutter user interfaces.
version: 0.0.2
repository: https://github.com/odroe/odroe/tree/main/pub/setup
homepage: https://odroe.dev
resolution: workspace

topics:
  - framework
  - reactive
  - composition
  - state-management
  - user-interface

funding:
  - https://github.com/sponsors/medz

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  oref: ^0.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
